---
title: "Exploring Customer Non-Verbal Communication Preferences in a Hotel"
author: 
  - Faghani, Amirarsalan[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 21080056, [Github Repo](https://github.com/amirarsalanfgh/midterm1.git)








# Introduction


When it comes to the hospitality industry one of the most critical factors for success is effective communication  customers. Understanding customers  needs and preferences is key to provid them with the best possible experience and nonverbal communication plays a significant role in this process. Nonverbal communication refers to the use of body language, facial expressions and other nonverbal cues to convey messages and emotions.

To explore the importance of nonverbal communication the hospitality industry a survey was conducted with 73 customers of hotel. The customers were between the ages of 24 and 81 and included both new and returning customers. The survey focused on the essential components of the nonverbal communication system including kinesic, paralanguage proxemic and chronemic subsystems.

The survey aimed to identify the communication preferences of the hotels customers by evaluating the indicators that make up these subsystems. A total of 22 variables were analyzed, which were considered feasible to evaluate by the hotels clientele.

By understanding customers  nonverbal communication preferences, hotels can better cater to their needs and create a more positive experience for them. This study aims to provide insights into the importance of nonverbal communication in the hospitality industry and its role in enhancing customer satisfaction.



## Literature Review

When planning a trip, choosing accommodation, tourists often rely on online reviews help them make informed decisions. In recent years online reviews have become an increasingly important source of information for travelers [@ahani2019revealing][@garcia2012lexicon]. Nonverbal communication is also key in the hospitality industry as it can greatly impact tourists satisfaction and overall experience [@islam2021nonverbal]. User-generated content in online travel communities can a significantly influence tourists' decision-making process as noted by Wang and Fesenmaier [@wang2004towards]. In order to develop sustainable tourism strategies, it s crucial to take into account tourists  preferences and opinions, as highlighted by Tusell et al. [@tusell2021improvement]. Additionally, it's worth noting that the book "Nonverbal Communication" by Burgoon, Manusov, and Guerrero [@burgoon2016nonverbal] provides a comprehensive overview of the topic, which may be useful for further research.
.





\newpage
# References {#references}
<div id="refs"></div>

